[package]
name = "scratchstack-aws-principal"
description = "Principal types for AWS/AWS-like services"
version = "0.2.0"
authors = ["David Cuthbert <dacut@kanga.org>"]
edition = "2018"
license = "MIT"

[features]
service = []

[dependencies]
log = "^0.4"
